apiVersion: v1
kind: Pod
metadata:
  name: fm-rox-go-sdk
spec:
  serviceAccountName: ops-gcr-rw
  containers:    
    - name: server
      image: golang:1.18
      tty: true
      resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
    - name: rox-proxy
      image: rollout/simple-proxy
      tty: true
      ports:
        - containerPort: 8080
      resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
