apiVersion: v1
kind: Pod
metadata:
  name: fm-rox-go-sdk
spec:
  serviceAccountName: ops-gcr-rw
  containers:    
    - name: server
      image: golang:1.18
      tty: true
      resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
