name: Unit Tests

on: [push]

jobs:
  unit_tests:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: go test ./core/...
        working-directory: ./v5
